version: "2.0"
services:
 devcontainer:
    build: 
      context: .
      dockerfile: ./robot_src/Dockerfile
    container_name: Integration_test    
    image: test_report
    command:
      run robot test.robot
      --reporter-html-export /etc/robot/results/report.html
      --reporter-html-export /etc/robot/results/log.html
    volumes:
     - ./robot_src:/etc/robot

   
      



      
