name: docker-compose-apitest
on: 

# schedule:
 # - cron: '0 */6 * * 5'    # https://crontab.guru/ #
  
#   push:                   # PUSH ON BRANCH MAIN
#     branches:
#      - 'main'
      
  workflow_dispatch:       # MANUAL EXECUTION 

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: <<<<<-------- Running Docker API tests ------->>>>
        run: docker-compose -f docker-compose-api.yml up 
        
      # - name: Run Docker 2
      #   run: docker-compose -f docker-compose.yml -f docker-compose.qa.yml up -d
        
      - name: =========  Attaching  Report  ===========
        uses: actions/upload-artifact@v2
        with:
          name: Report
          path: api/report/report.html
